//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso_Empleados
    {
        public string Nombre_Completo { get; set; }
        public Nullable<int> Año_de_ingreso { get; set; }
        public Nullable<int> Mes_de_ingreso { get; set; }
        public Nullable<int> Dia_de_ingreso { get; set; }
    }
}
